# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hadee\OneDrive\바탕 화면\speed_quiz\speed_quiz\speed_quiz_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1128, 852)
        Dialog.setMinimumSize(QtCore.QSize(1128, 852))
        Dialog.setMaximumSize(QtCore.QSize(1128, 852))
        Dialog.setToolTipDuration(0)
        self.question = QtWidgets.QTextEdit(Dialog)
        self.question.setGeometry(QtCore.QRect(30, 160, 1071, 471))
        self.question.setStyleSheet("font: 17pt \"상상토끼 문래러\";")
        self.question.setReadOnly(True)
        self.question.setOverwriteMode(False)
        self.question.setTabStopWidth(80)
        self.question.setCursorWidth(0)
        self.question.setObjectName("question")
        self.title = QtWidgets.QLineEdit(Dialog)
        self.title.setGeometry(QtCore.QRect(30, 30, 691, 81))
        self.title.setMinimumSize(QtCore.QSize(691, 81))
        self.title.setMaximumSize(QtCore.QSize(691, 81))
        self.title.setStyleSheet("font: 30pt \"상상토끼 꽃길\";\n"
"color: rgb(72, 144, 216);")
        self.title.setText("")
        self.title.setFrame(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setDragEnabled(True)
        self.title.setReadOnly(True)
        self.title.setObjectName("title")
        self.time = QtWidgets.QLineEdit(Dialog)
        self.time.setGeometry(QtCore.QRect(1000, 30, 91, 81))
        self.time.setStyleSheet("font: 18pt \"상상토끼 문래러\";\n"
"color: rgb(255, 85, 127);")
        self.time.setText("")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setDragEnabled(True)
        self.time.setReadOnly(True)
        self.time.setObjectName("time")
        self.answer = QtWidgets.QLineEdit(Dialog)
        self.answer.setGeometry(QtCore.QRect(780, 740, 301, 71))
        self.answer.setStyleSheet("font: 16pt \"상상토끼 신비는일곱살\";\n"
"color: rgb(130, 130, 130);")
        self.answer.setText("")
        self.answer.setFrame(False)
        self.answer.setObjectName("answer")
        self.p = QtWidgets.QPushButton(Dialog)
        self.p.setEnabled(False)
        self.p.setGeometry(QtCore.QRect(680, 730, 101, 91))
        self.p.setAcceptDrops(True)
        self.p.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p.setAutoFillBackground(False)
        self.p.setText("")
        self.p.setCheckable(True)
        self.p.setChecked(False)
        self.p.setAutoRepeat(True)
        self.p.setAutoExclusive(True)
        self.p.setAutoDefault(False)
        self.p.setDefault(False)
        self.p.setFlat(True)
        self.p.setObjectName("p")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1128, 852))
        self.graphicsView.setMinimumSize(QtCore.QSize(1128, 852))
        self.graphicsView.setMaximumSize(QtCore.QSize(1128, 852))
        self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/background.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.question.raise_()
        self.title.raise_()
        self.time.raise_()
        self.answer.raise_()
        self.p.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.question.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'상상토끼 문래러\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
