# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hadee\OneDrive\바탕 화면\speed_quiz\speed_quiz\start_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1128, 852)
        Dialog.setMinimumSize(QtCore.QSize(1128, 852))
        Dialog.setMaximumSize(QtCore.QSize(1128, 852))
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1128, 852))
        self.graphicsView.setMinimumSize(QtCore.QSize(1128, 852))
        self.graphicsView.setMaximumSize(QtCore.QSize(1128, 852))
        self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/background.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.start = QtWidgets.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(420, 580, 321, 101))
        self.start.setStyleSheet("font: 36pt \"상상토끼 꽃집막내딸\";")
        self.start.setObjectName("start")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(360, 130, 761, 101))
        self.lineEdit.setStyleSheet("font: 48pt \"상상토끼 꽃집막내딸\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(115, 178, 213);\n"
"")
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start.setText(_translate("Dialog", "도 전"))
        self.lineEdit.setText(_translate("Dialog", "나도 아인슈타인!"))
import background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
